### ISSUE TITLE
How to keep project source code from ohif to local

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1653]
Hi @dannyrb And everyone,

We see this project is not stable now, We want to keep your code but we want to code directly in this source code to change the UI and somethings.
We forked to our local, but when you have something update, we pull them but have lots of conflict.
Do you have any ideal for us?

**Comment by dannyrb** [comment]
@trung1704ptit, it depends on what your customization goals are for the viewer. We version the `platform/viewer` project, which is what 90% of our users consume, based almost entirely on it's `application configuration` file. It's a fully featured application, so we can't make any promises to our users that every change to it's internals won't break some tacked on functionality, or we would need to author a major version for, well, every change.

### Some guidance:

1. If you encounter bugs or defects, report the issue and contribute a fix in a PR. This benefits the entire community, and makes maintaining a fork easier.
2. If there is some functionality that is not yet supported by extensions, consider reaching out so that we can expand what we do support, and decrease the likelihood that you will need to maintain a fork. We don't always have the bandwidth to author these changes, but can approve, provide guidance, and review PRs that expand support.

Each project is independently versioned and provides different ways to extend and configure its behavior. If you find yourself mucking about in the internals, you're probably doing something that is "brittle" and inherently prone to breaking. Help us identify these missing extension points, and consider authoring changes that make it less likely that updates to a project will leave you in a tough spot squinting at a 30,000 line merge commit.

### Our goals for OHIF, from an extensibility/forking stand-point:

- That `@ohif/viewer` and the progressive web application built by OHIF can support > 90% of our users with only simple configuration file changes
- That most users that would normally fork the project are able to avoid doing so by packaging custom logic into simple OHIF extensions
- That when users need truly custom UI and experiences, they can override one or more projects in the monorepo so they can leverage the bulk of the application logic contained in other packages, but still achieve the level of customization they require

We intend to develop and deliver a new concept that expands our current extensibility through "modes". Think "install-able and shareable workflows" that will further decrease the need to fork. We are working at the pace our current grant affords us the ability to.

**Comment by eolasd** [comment]
I have a similar position to this. Currently maintaining a custom clone, but will also contribute back anything I can to help the project. 
The main reasons for a custom repo are mostly UI/Cosmetic, but I couldn't find a way to do them without modifying code:

1. Removing the header on mobile to give more screen space to images.
2. Removing extra buttons not required on mobile (zoom, pan etc..) - had to just remove them in the cornerstone toolbar extension directly (maybe forking just the extension is the way to go here?)
3. Whitelabel features (I think this is fixed now with the config file)

I am sure there is probably easier ways to do this - but I am not familiar enough yet with the extensions architecture, and would rather not just 'display:none' everything in CSS but still compile them - bundle size is important!

**Comment by dannyrb** [comment]
I do wish we had the funding to offer better support for mobile resolutions. It feels silly that all of our Viewports support touch and pointer interactions, but our limiting factor for mobile are a few CSS rules and regression testing costs. FWIW, there are some design changes coming that make it _easier_ to accommodate mobile, but we're still not 100% there.

> Removing extra buttons not required on mobile (zoom, pan etc..) - had to just remove them in the cornerstone toolbar extension directly (maybe forking just the extension is the way to go here?)

Today, extensions kind of just glom everything in them into the Viewer route. Moving forward, we're working on a concept called _modes_ that lets you choose and configure which parts of extensions should be leveraged by one or more viewing routes. This makes it easier to reuse and share functionality without the need to fork an extension.

> Whitelabel features

The logo feature did receive a recent fix. Use of color variables could be better / reviewed.

> Removing the header on mobile to give more screen space to images

If there's a good breakpoint to apply this change, and it looks okay, more than happy to accept a PR.

> Perhaps better understanding of the extension system would help here?

After the modes changes are completed, next on the docket is revising our docs and providing some high level training via video courses at https://ohiftraining.com

**Comment by eolasd** [comment]
Thanks for the info @dannyrb. Great to know the project is continuously moving forward. The training site looks awesome.

I'll see if I can do a small PR for the mobile header.
