### ISSUE TITLE
MPR Not working with V3-stable

### ISSUE THREAD

**Issue by mokbelt** [OHIF/Viewers#3049]
MPR is not working on v3-stable after building.
It working normally with V2.

**Comment by mokbelt** [comment]
When I click on MPR, I get this error, and nothing opens on the UI (howhewver working normally on V2).
I am using Chrome.

createFloat32SharedArray.js:3 Uncaught (in promise) Error: Your page is NOT cross-origin isolated, see https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated
    at cm (createFloat32SharedArray.js:3:15)
    at sw (cornerstoneStreamingImageVolumeLoader.js:50:26)
    at Zt (volumeLoader.js:42:30)
    at Module.Kt (volumeLoader.js:76:24)
    at e.<anonymous> (CornerstoneCacheService.ts:181:37)
    at c (CornerstoneCacheService.ts:2:1)
    at Generator._invoke (CornerstoneCacheService.ts:2:1)
    at Generator.next (CornerstoneCacheService.ts:2:1)
    at aN (CornerstoneCacheService.ts:2:1)
    at o (CornerstoneCacheService.ts:2:1)

![image](https://user-images.githubusercontent.com/56265911/204652431-fa09fb40-bb60-4774-8e33-faf614f46829.png)

**Comment by ranasrule** [comment]
> When I click on MPR, I get this error, and nothing opens on the UI (howhewver working normally on V2). I am using Chrome.
> 
> createFloat32SharedArray.js:3 Uncaught (in promise) Error: Your page is NOT cross-origin isolated, see https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated at cm (createFloat32SharedArray.js:3:15) at sw (cornerstoneStreamingImageVolumeLoader.js:50:26) at Zt (volumeLoader.js:42:30) at Module.Kt (volumeLoader.js:76:24) at e. (CornerstoneCacheService.ts:181:37) at c (CornerstoneCacheService.ts:2:1) at Generator._invoke (CornerstoneCacheService.ts:2:1) at Generator.next (CornerstoneCacheService.ts:2:1) at aN (CornerstoneCacheService.ts:2:1) at o (CornerstoneCacheService.ts:2:1)
> 
> ![image](https://user-images.githubusercontent.com/56265911/204652431-fa09fb40-bb60-4774-8e33-faf614f46829.png)

Already discussed  and solved at the below link

https://github.com/OHIF/Viewers/issues/3033

**Comment by mokbelt** [comment]
@ranasrule thank you!
Can you please where shall I put those headers? in the nginx config?

**Comment by ranasrule** [comment]
> @ranasrule thank you! Can you please where shall I put those headers? in the nginx config?

yes

**Comment by sedghi** [comment]
I will add a check for cross origin isolated to warn user that you can't use MPR if not

**Comment by mokbelt** [comment]
I added this on my nginx conf on ubuntu 20 but still getting: Uncaught (in promise) Error: Your page is NOT cross-origin isolated, see https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated

This is my conf file:

server {
listen 3001;
location / {
root /ohifv3/Viewers-3-stable/platform/viewer/dist;
index index.html index.htm;
try_files $uri $uri/ /index.html;

add_header Cross-Origin-Opener-Policy same-origin;
add_header Cross-Origin-Embedder-Policy require-corp;
add_header Cross-Origin-Resource-Policy same-origin;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

}
error_page 500 502 503 504 /50x.html;
location = /50x.html {
root /ohifv3/Viewers-3-stable/platform/viewer/dist;
}
}

**Comment by Georift** [comment]
@mokbelt Unless you're running on localhost, you'll probably also need to ensure you have HTTPS enabled.

**Comment by sedghi** [comment]
I recently added the `/debug` route to show some info, can you paste here your `/debug`? @mokbelt

**Comment by leon1227** [comment]
> @mokbelt Unless you're running on localhost, you'll probably also need to ensure you have HTTPS enabled.

Just be curious: why HTTPS enabled is a prerequisite for MPR?

**Comment by Georift** [comment]
@leon1227 Been a while since I've looked at this, but I believe MPR makes use of `SharedArrayBuffer`'s which [requires you're running in a Secure Context.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements)

**Comment by sedghi** [comment]
we know have dedicated documentation page for these questions https://docs.ohif.org/deployment/cors

**Comment by sedghi** [comment]
You can run the viewer without the SAB, please refer to the docs
