### ISSUE TITLE
[Bug] Enabling useCPURendering breaks the app

### ISSUE THREAD

**Issue by Omid-Heydarzadeh** [OHIF/Viewers#4564]
### Describe the Bug

Enabling useCPURendering in app config file breaks the app
Also, when it is enabled, cornerstone will still logs "using GPU rendering" in the console.
This issue is relevant to OHIF v3.8.5, v3.9.1 and v3.10.0-beta.12

### Steps to Reproduce

1. add `useCPURendering: true` to the app config (e.g. `platform/app/public/config/default.js`)
2. run `yarn dev`
3. open any of studies using basic viewer

### The current behavior

This error shows up:

Context: Route /viewer
Error Message: Cannot destructure property 'direction' of 'metadata' as it is undefined.
Stack: TypeError: Cannot destructure property 'direction' of 'metadata' as it is undefined.
    at StackViewport.getCameraCPU (http://localhost:3000/app.js:2623:17)
    at evaluate (http://localhost:3000/extensions_cornerstone_src_index_tsx.js:5012:31)
    at http://localhost:3000/app.js:134721:55
    at Array.map (<anonymous>)
    at props.evaluate (http://localhost:3000/app.js:134721:38)
    at evaluateButtonProps (http://localhost:3000/app.js:134926:43)
    at http://localhost:3000/app.js:134978:48
    at Array.map (<anonymous>)
    at http://localhost:3000/app.js:134978:36
    at Array.reduce (<anonymous>)
    

### The expected behavior

OHIF should load and view selected study instance correctly using CPU renderer.

### OS

Windows 11 Enterprise 23H2

### Node version

20.11.1

### Browser

Chrome 131.0.6778.86, Firefox 133

**Comment by sedghi** [comment]
if you update cornerstone version in OHIF it should be fixed

**Comment by Omid-Heydarzadeh** [comment]
Can you help me find files that need to be modified? Also which version of cornerstone is needed to fix this issue?

Primarily, I need to resolve this issue on the latest stable version, which currently is `OHIF v3.9.2` and the issue is not resolved on this version yet.

I tried to manually update all cornerstone packages in all `package.json` files with latest compatible versions, but it didn't work.
Also, I tried to cherry pick newest version bump commits from master branch and it didn't work, either.

Although, cpu rendering is working on `OHIF v3.10.0-beta.18`, it is not stable yet. For example when I click the reset view button this error occurs:

on Chrome: 

Context: Route /viewer
Error Message: Cannot read properties of undefined (reading 'isA')
Stack: TypeError: Cannot read properties of undefined (reading 'isA')
    at actorIsA (http://localhost:3000/app.js:19124:27)
    at isImageActor (http://localhost:3000/app.js:19120:13)
    at StackViewport.getTransferFunction (http://localhost:3000/app.js:2861:82)
    at StackViewport._resetProperties (http://localhost:3000/app.js:2568:39)
    at StackViewport.resetProperties (http://localhost:3000/app.js:2554:14)
    at resetViewport (http://localhost:3000/extensions_cornerstone_src_index_tsx.js:1293:33)
    at CommandsManager.runCommand (http://localhost:3000/app.js:125670:14)
    at http://localhost:3000/app.js:125724:23
    at Array.forEach (<anonymous>)
    at CommandsManager.run (http://localhost:3000/app.js:125717:14)
    


on Firefox:

Context: Route /viewer
Error Message: actorToCheck is undefined
Stack: actorIsA@http://localhost:3000/app.js:19124:13
isImageActor@http://localhost:3000/app.js:19120:13
getTransferFunction@http://localhost:3000/app.js:2861:82
_resetProperties@http://localhost:3000/app.js:2568:39
resetProperties@http://localhost:3000/app.js:2554:14
resetViewport@http://localhost:3000/extensions_cornerstone_src_index_tsx.js:1293:16
runCommand@http://localhost:3000/app.js:125670:14
../../core/src/classes/CommandsManager.ts/run/<@http://localhost:3000/app.js:125724:23
run@http://localhost:3000/app.js:125717:14
recordInteraction@http://localhost:3000/app.js:135531:27
../../core/src/hooks/useToolbar.tsx/useToolbar/onInteraction<@http://localhost:3000/app.js:128267:20
onClick@http://localhost:3000/app.js:179858:20
handleOnClick@http://localhost:3000/app.js:162658:12
callCallback@http://localhost:3000/app.js:383976:14
invokeGuardedCallbackDev@http://localhost:3000/app.js:384025:16
invokeGuardedCallback@http://localhost:3000/app.js:384089:31
invokeGuardedCallbackAndCatchFirstError@http://localhost:3000/app.js:384103:25
executeDispatch@http://localhost:3000/app.js:388853:42
processDispatchQueueItemsInOrder@http://localhost:3000/app.js:388885:22
processDispatchQueue@http://localhost:3000/app.js:388898:37
dispatchEventsForPlugins@http://localhost:3000/app.js:388909:23
../../../node_modules/react-dom/cjs/react-dom.development.js/dispatchEventForPluginEventSystem/<@http://localhost:3000/app.js:389100:12
batchedUpdates$1@http://localhost:3000/app.js:405986:12
batchedUpdates@http://localhost:3000/app.js:383803:12
dispatchEventForPluginEventSystem@http://localhost:3000/app.js:389099:17
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay@http://localhost:3000/app.js:386277:38
dispatchEvent@http://localhost:3000/app.js:386269:84
dispatchDiscreteEvent@http://localhost:3000/app.js:386242:18

**Comment by Omid-Heydarzadeh** [comment]
Manually updating cornerstone fixes intial error of cpu rendering but it introduces another bug that makes the reset view button throws an error.

on Chrome:

Context: Route //viewer
Error Message: Cannot read properties of undefined (reading 'isA')
Stack: TypeError: Cannot read properties of undefined (reading 'isA')
    at actorIsA (webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/utilities/actorCheck.js:11:27)
    at isImageActor (webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/utilities/actorCheck.js:7:13)
    at StackViewport.getTransferFunction (webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/RenderingEngine/StackViewport.js:983:82)
    at StackViewport._resetProperties (webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/RenderingEngine/StackViewport.js:690:39)
    at StackViewport.resetProperties (webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/RenderingEngine/StackViewport.js:676:14)
    at resetViewport (webpack-internal:///../../../extensions/cornerstone/src/commandsModule.ts:589:33)
    at CommandsManager.runCommand (webpack-internal:///../../core/src/classes/CommandsManager.ts:155:14)
    at eval (webpack-internal:///../../core/src/classes/CommandsManager.ts:209:23)
    at Array.forEach (<anonymous>)
    at CommandsManager.run (webpack-internal:///../../core/src/classes/CommandsManager.ts:202:14)
    

on Firefox:


Context: Route //viewer
Error Message: actorToCheck is undefined
Stack: actorIsA@webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/utilities/actorCheck.js:11:13
isImageActor@webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/utilities/actorCheck.js:7:13
getTransferFunction@webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/RenderingEngine/StackViewport.js:983:82
_resetProperties@webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/RenderingEngine/StackViewport.js:690:39
resetProperties@webpack-internal:///../../../node_modules/@cornerstonejs/core/dist/esm/RenderingEngine/StackViewport.js:676:14
resetViewport@webpack-internal:///../../../extensions/cornerstone/src/commandsModule.ts:589:16
runCommand@webpack-internal:///../../core/src/classes/CommandsManager.ts:155:14
run/<@webpack-internal:///../../core/src/classes/CommandsManager.ts:209:23
run@webpack-internal:///../../core/src/classes/CommandsManager.ts:202:14
recordInteraction@webpack-internal:///../../core/src/services/ToolBarService/ToolbarService.ts:258:27
useToolbar/onInteraction<@webpack-internal:///../../core/src/hooks/useToolbar.tsx:34:20
onClick@webpack-internal:///../../ui/src/components/ToolbarButton/ToolbarButton.tsx:69:20
handleOnClick@webpack-internal:///../../ui/src/components/IconButton/IconButton.tsx:91:12
callCallback@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:4164:14
invokeGuardedCallbackDev@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:4213:16
invokeGuardedCallback@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:4277:31
invokeGuardedCallbackAndCatchFirstError@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:4291:25
executeDispatch@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9041:42
processDispatchQueueItemsInOrder@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9073:22
processDispatchQueue@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9086:37
dispatchEventsForPlugins@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9097:23
dispatchEventForPluginEventSystem/<@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9288:12
batchedUpdates$1@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:26174:12
batchedUpdates@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:3991:12
dispatchEventForPluginEventSystem@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9287:17
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:6465:38
dispatchEvent@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:6457:84
dispatchDiscreteEvent@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:6430:18
EventListener.handleEvent*addEventBubbleListener@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:6687:10
addTrappedEventListener@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9191:29
listenToNativeEvent@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9129:26
listenToAllSupportedEvents/<@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9140:30
listenToAllSupportedEvents@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:9135:21
createRoot@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:29420:29
createRoot$1@webpack-internal:///../../../node_modules/react-dom/cjs/react-dom.development.js:29850:10
exports.createRoot@webpack-internal:///../../../node_modules/react-dom/client.js:9:16
@webpack-internal:///./index.js:56:76
promise callback*@webpack-internal:///./index.js:40:79
./index.js@http://localhost:3001/app.js:8146:1
options.factory@http://localhost:3001/app.js:58455:31
__webpack_require__@http://localhost:3001/app.js:57833:32
@http://localhost:3001/app.js:59161:56
@http://localhost:3001/app.js:59163:12
